version: "3.8"
services:
  go-api:
    build: ./go-api
    ports:
      - "8080:8080"
    environment:
      - NODE_API_URL=http://node-api:3000
    depends_on:
      - node-api

  node-api:
    build: ./node-api
    ports:
      - "3000:3000"